### ISSUE TITLE
crashes right after testing

### ISSUE THREAD

**Issue by kaloun34** [MiSTer-devel/Arcade-TropicalAngel_MiSTer#5] opened 2023-10-16 08:51 UTC
Hello
The latest version of the core does not work.
It crashes right after testing

**Comment by birdybro** [comment] 2023-10-31 21:27
Sorry I didn't notice this in my inbox earlier, I'll take a look. :)

**Comment by birdybro** [comment] 2023-10-31 22:15
I'm willing to bet this will work fine, gonna test it myself later, just place-holdering it here. I just did a simple template update, that shouldn't impact anything, but I think maybe the release I pushed out might be corrupt, I couldn't reproduce it's hash with compiling multiple times.

[TropicalAngel_20231031.zip](https://github.com/MiSTer-devel/Arcade-TropicalAngel_MiSTer/files/13221730/TropicalAngel_20231031.zip)

**Comment by birdybro** [comment] 2023-11-01 00:00
Just tested at home, it's not crashing for me after running for quite some time, neither is the one I just compiled. Are you able to reproduce this issue still?

**Comment by birdybro** [comment] 2024-01-16 18:21
Stability should be improved now thanks to Robert Peip's recent changes to the framework. I couldn't get it to crash so I'm closing this issue.

**Closed as completed by birdybro** 2024-01-16 18:21 UTC
